package modelo;

public enum Categoria {

	ENTERO,
	REAL,
	IDENTIFICADOR,
	RESERVADA,
	ARITMETICO,
	RELACIONAL,
	LOGICO,
	ASIGNACION,
	INCREMENTO_DECREMENTO,
	PARENTESIS_APERTURA,
	PARENTESIS_CIERRE,
	LLAVE_APERTURA,
	LLAVE_CIERRE,
	TERMINAL,
	SEPARADOR,
	HEXADECIMAL,
	CADENA,
	DESCONOCIDO, 
	CORCHETE_APERTURA,
	CORCHETE_CIERRE, 
	PUNTO, 
	DOS_PUNTOS,
	COMENTARIO_LINEA,
<<<<<<< HEAD
	COMENTARIO_BLOQUE,
	CARACTER
=======
	COMENTARIO_BLOQUE
>>>>>>> parent of 79a2af7... Falto meter estos archivos al commit anterior GG
	
}
